# Generated by Django 3.0.8 on 2020-08-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('smptserver', models.CharField(max_length=20)),
                ('smptemail', models.CharField(max_length=20)),
                ('smptpassword', models.CharField(max_length=20)),
                ('smtpport', models.CharField(blank=True, max_length=5)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('aboutus', models.TextField()),
                ('references', models.TextField()),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=20)),
                ('create_at', models.DateTimeField(verbose_name='date published')),
                ('update_at', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
