# Generated by Django 3.0.8 on 2020-08-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('model_year', models.CharField(max_length=200)),
                ('engine_capacity', models.CharField(max_length=200)),
                ('gear', models.CharField(max_length=200)),
                ('fuel', models.CharField(max_length=200)),
                ('body_type', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('slug', models.SlugField()),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=20)),
                ('create_at', models.DateTimeField(verbose_name='date published')),
                ('update_at', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
