# Generated by Django 3.0.8 on 2020-08-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='status',
            new_name='durum',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='body_type',
            new_name='fiyat',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='create_at',
            new_name='ilan_tarihi',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='brand',
            new_name='kasa_tipi',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='engine_capacity',
            new_name='marka',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='fuel',
            new_name='model_yılı',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='gear',
            new_name='motor_hacmi',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='image',
            new_name='resim',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='model_year',
            new_name='vites',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='price',
            new_name='yakıt',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='update_at',
        ),
    ]
