# Generated by Django 3.0.8 on 2020-08-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='resim',
        ),
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
