# Generated by Django 3.0.8 on 2020-08-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20200810_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='image',
            new_name='resim',
        ),
    ]
