# Generated by Django 3.0.8 on 2020-08-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20200810_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='resim',
            new_name='image',
        ),
    ]
