# Generated by Django 3.0.8 on 2020-08-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20200810_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='image',
        ),
        migrations.AddField(
            model_name='cars',
            name='resim',
            field=models.ImageField(blank=True, upload_to='uploads/images/'),
        ),
    ]
