# Generated by Django 3.0.8 on 2020-08-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20200810_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='resim',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
