# Generated by Django 3.0.8 on 2020-08-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20200811_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='detay',
            field=models.TextField(blank=True),
        ),
    ]
