# Generated by Django 3.0.8 on 2020-08-11 13:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_cars_detay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='detay',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
