# Generated by Django 3.0.8 on 2020-08-12 13:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20200811_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='detay',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
