# Generated by Django 3.0.8 on 2020-08-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_cars_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='resim',
        ),
    ]
