# Generated by Django 3.0.8 on 2020-08-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_remove_cars_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='resim',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
