# Generated by Django 3.0.8 on 2020-08-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_auto_20200816_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
    ]
