# Generated by Django 3.0.8 on 2020-08-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_auto_20200816_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='subject',
        ),
    ]
