# Generated by Django 3.0.8 on 2020-08-21 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0020_auto_20200817_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=70)),
                ('checkin', models.DateField(null=True)),
                ('checkout', models.DateField(null=True)),
                ('status', models.CharField(choices=[('New', 'Yeni'), ('Accepted', 'Onaylandı'), ('Cancelled', 'Reddedildi')], default='New', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=25)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Cars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
