# Generated by Django 3.0.8 on 2020-08-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_remove_reservation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='update_at',
        ),
    ]
